name: DollLibCorrect
description: Doll rendering library
version: 2.2.0
homepage: https://github.com/FarragoFiction/DollLibCorrect
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.0
  RenderingLib:
    git:
      url: git://github.com/FarragoFiction/RenderingLib.git
      ref: Dart-2.2.0
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: Dart-2.2.0
  LoaderLib:
    git:
      url: git://github.com/FarragoFiction/LoaderLib.git
      ref: Dart-2.2.0
  TextEngine:
    git:
      url: git://github.com/FarragoFiction/TextEngine.git
      ref: Dart-2.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0


