name: DollLibCorrect
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: JR <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  js: ^0.6.0
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0


transformers:
- - dart_to_js_script_rewriter
