name: DollLibCorrect
description: Doll rendering library
version: 2.12.0
homepage: https://github.com/FarragoFiction/DollLibCorrect
author: jadedResearcher, paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.0
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_test: any



