name: DollLibCorrect
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: JR <email@example.com>

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  js: ^0.6.0
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  source_maps: any
  source_map_stack_trace: any
  package_resolver: any


transformers:
- $dart2js:
    sourceMaps: true
    commandLineOptions: [--fast-startup, --trust-type-annotations]